### PR TITLE
fix(issue-88): Fix decoding asn1 code with empty bitstring

### LINKED ISSUE #88: Panic during ASN1 data parsing
data:
```
6065060a2a864886f7120102020303007e553053a003020105a10302011ea411180f32303235303230383130333035365aa5050203056b0ea603020129a9091b075442542e434f4daa1d301ba003020101a11430121b1077696e2d39353663716f73736a746624
```

### PR DESCRIPTION
**Pull request by grok-rs**
image

This pull request introduces a validation check in the BitString decoder to explicitly reject any BitString with no content bytes

### Test string
```sh
6065060a2a864886f7120102020303007e553053a003020105a10302011ea411180f32303235303230383130333035365aa5050203056b0ea603020129a9091b075442542e434f4daa1d301ba003020101a11430121b1077696e2d39353663716f73736a746624
```

closes #88

### CODE REVIEW

File: src/asn1/scheme/strings.rs [hunk 1]
```diff
@@ -68,15 +68,24 @@ pub struct BitStringNodeProps {
...
+        bits
+    } else {
+        String::new()
+    };
+
+    let display_bits = if bits.len() >= bits_amount {
+        &bits[0..bits_amount]
+    } else {
+        &bits[..]
+    };
```
Comment (TheBestTvarynka) [inline src/asn1/scheme/strings.rs:88]: this code can be simplified:

```suggestion
    let display_bits = &bits[0..bits_amount.min(bits.len())];
```

**Review by TheBestTvarynka — APPROVED** [review]
good code. Thank you :+1:

**Review by TheBestTvarynka — APPROVED** [review]
Thank you!
